"""
make_table15.py — Auxiliary deployment-side study (temporal smoothing grid).

Inputs : 007_public_repo_v2/study/reports/EfficientNetV2B0/FULL/
         temporal_smoothing_optimization.json
Outputs: paper/tables/T15_temporal_smoothing.tex

Renders only a compact best-per-window slice (6 rows) plus the optimum
flagged with a star. The full 36-row grid is kept in JSON only to avoid
table bloat.
"""
from __future__ import annotations
from pathlib import Path
import json
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = (ROOT.parent / "007_public_repo_v2" / "study" / "reports"
       / "EfficientNetV2B0" / "FULL"
       / "temporal_smoothing_optimization.json")
OUT = ROOT / "tables" / "T15_temporal_smoothing.tex"


def main():
    d = json.loads(SRC.read_text())
    rows = pd.DataFrame(d["raw_results"])
    # Best per window (max accuracy with FPR=0 if possible; else best score)
    best = (rows.sort_values(["N", "score"], ascending=[True, False])
                 .drop_duplicates("N"))
    optimal_n = d["optimal_N"]
    optimal_t = d["optimal_threshold"]
    body_rows = []
    for _, r in best.iterrows():
        flag = r"$^{\star}$" if (int(r["N"]) == optimal_n
                                  and abs(r["threshold"] - optimal_t) < 1e-6) else ""
        body_rows.append(
            f"{int(r['N'])} & {r['threshold']:.1f} & "
            f"{r['accuracy']*100:.2f} & {r['fpr']*100:.2f} & "
            f"{r['score']:.4f}{flag} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_table15.py from
% reports/EfficientNetV2B0/FULL/temporal_smoothing_optimization.json
\begin{table}[t]
\centering
\caption{Best per-window result of the temporal-smoothing grid search
on the deployment-side EfficientNetV2B0/\texttt{FULL} stream
($N\!\in\!\{1,3,5,7,10,15\}$, $\theta\!\in\![0.4,0.9]$, score $=$
accuracy $-$ false-positive rate). The optimum ($\star$) is the
single-frame, low-threshold setting; longer windows trade accuracy for
false positives at this confidence floor.}
\label{tab:temporal_smoothing}
\begin{tabular}{rrrrl}
\toprule
$N$ & $\theta$ & Accuracy (\%) & FPR (\%) & Score \\
\midrule
""" + "\n".join(body_rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"[SAVED] {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
