"""
make_tables.py — Generate IEEE-style booktabs LaTeX tables.

Inputs : 007_public_repo_v2/study/reports/Q1_Reports/Q1_Table*.csv
         paper/stats/per_config_summary.csv
         paper/stats/pairwise_results.csv

Outputs: paper/tables/T01_dataset_inventory.tex
         paper/tables/T02_model_complexity.tex
         paper/tables/T03_main_results.tex
         paper/tables/T04_ablation_impact.tex
         paper/tables/T05_generalization_gap.tex
         paper/tables/T06_tune_strategy_effect.tex
         paper/tables/T07_head_strategy_effect.tex
         paper/tables/T08_synthetic_significance.tex

All tables use \\toprule \\midrule \\bottomrule (booktabs), no vertical lines,
ready for IEEEtran via \\usepackage{booktabs}.
"""
from __future__ import annotations
from pathlib import Path
import pandas as pd
import numpy as np
import json

ROOT = Path(__file__).resolve().parents[1]
Q1 = ROOT.parent / "007_public_repo_v2" / "study" / "reports" / "Q1_Reports"
STATS = ROOT / "stats"
OUT = ROOT / "tables"
OUT.mkdir(parents=True, exist_ok=True)

INV = json.loads((ROOT / "data_provenance" / "raw_dataset_inventory.json").read_text())


def latex_escape(s: str) -> str:
    return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def write_table(path: Path, body: str):
    path.write_text(body, encoding="utf-8")
    print(f"[SAVED] {path}  ({path.stat().st_size} bytes)")


# ---------------------------------------------------------------- T01
def t01_dataset_inventory():
    cls = INV["samples_per_class"]
    total = INV["total_raw_images"]
    rows = []
    for c, n in cls.items():
        rows.append(f"{latex_escape(c)} & {n:,} & {n/total*100:.1f} \\\\")
    rows.append(f"\\midrule\nTotal & {total:,} & 100.0 \\\\")

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table}[t]
\centering
\caption{Raw image inventory (pre-synthesis) sourced from a combined Kaggle
RPS corpus and a HaGRID-30k slice. The \texttt{none} class is generated
downstream from background scenes and is therefore not present in raw.}
\label{tab:dataset_inventory}
\begin{tabular}{lrr}
\toprule
Class & Image count & Share (\%) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write_table(OUT / "T01_dataset_inventory.tex", body)


# ---------------------------------------------------------------- T02
def t02_model_complexity():
    df = pd.read_csv(Q1 / "Q1_Table1_Model_Complexity.csv", sep=";")
    # Reduce to architecture × params (ignore tune strategy duplicates)
    df["params_M"] = df["Eğitilebilir Parametre Sayısı (Milyon)"].str.rstrip("M").astype(float)
    arch = df.groupby("Mimarisi")["params_M"].first().reset_index()
    arch = arch.rename(columns={"Mimarisi": "Backbone", "params_M": "Trainable Params (M)"})
    arch = arch.sort_values("Trainable Params (M)").reset_index(drop=True)

    rows = "\n".join(
        f"{latex_escape(r.Backbone)} & {r['Trainable Params (M)']:.2f} \\\\"
        for _, r in arch.iterrows()
    )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table}[t]
\centering
\caption{Trainable-parameter footprint of each backbone (head excluded).
Disk size varies by checkpoint format and is omitted for clarity.}
\label{tab:model_complexity}
\begin{tabular}{lr}
\toprule
Backbone & Trainable params (M) \\
\midrule
""" + rows + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write_table(OUT / "T02_model_complexity.tex", body)


# ---------------------------------------------------------------- T03
def t03_main_results():
    """Main result: per-backbone, FULL ablation, standard head, both tunes."""
    df = pd.read_csv(STATS / "per_config_summary.csv")
    cur = df[(df["ablation"] == "FULL") & (df["head"] == "standard")].copy()
    pivot = cur.pivot_table(index="model", columns="tune",
                            values=["acc_mean", "acc_std", "macro_f1_mean", "n_folds"],
                            aggfunc="first")
    rows = []
    for model in ["EfficientNetV2B0", "MobileNetV3Small", "ResNet50",
                  "DenseNet121", "VGG16"]:
        if model not in pivot.index:
            continue
        s_mean = pivot.loc[model, ("acc_mean", "standard")] * 100
        s_std = pivot.loc[model, ("acc_std", "standard")] * 100
        p_mean = pivot.loc[model, ("acc_mean", "progressive")] * 100
        p_std = pivot.loc[model, ("acc_std", "progressive")] * 100
        f1_s = pivot.loc[model, ("macro_f1_mean", "standard")] * 100
        f1_p = pivot.loc[model, ("macro_f1_mean", "progressive")] * 100
        n_std = int(pivot.loc[model, ("n_folds", "standard")]) if not pd.isna(pivot.loc[model, ("n_folds", "standard")]) else 0
        n_prog = int(pivot.loc[model, ("n_folds", "progressive")]) if not pd.isna(pivot.loc[model, ("n_folds", "progressive")]) else 0
        flag_s = "$^{*}$" if n_std < 5 else ""
        flag_p = "$^{*}$" if n_prog < 5 else ""
        rows.append(
            f"{latex_escape(model)} & "
            f"${s_mean:.2f} \\pm {s_std:.2f}$ & ${f1_s:.2f}$ & {n_std}{flag_s} & "
            f"${p_mean:.2f} \\pm {p_std:.2f}$ & ${f1_p:.2f}$ & {n_prog}{flag_p} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table*}[t]
\centering
\caption{Main in-distribution results on the FULL synthetic-augmentation pipeline,
standard classification head, image-grouped 5-fold cross-validation
(mean$\pm$std on validation accuracy, macro-F1 in \%); cells with n$<$5 are flagged~$^{*}$.}
\label{tab:main_results}
\begin{tabular}{lccrccc}
\toprule
 & \multicolumn{3}{c}{Standard fine-tuning} & \multicolumn{3}{c}{Progressive fine-tuning} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
Backbone & Acc.\ (\%) & Macro-F1 & Std $n$ & Acc.\ (\%) & Macro-F1 & Prog $n$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    write_table(OUT / "T03_main_results.tex", body)


# ---------------------------------------------------------------- T04
def t04_ablation_impact():
    df = pd.read_csv(Q1 / "Q1_Table5_Ablation_Impact.csv", sep=";")
    df = df.sort_values("Ortalama Başarı (%)", ascending=False)
    rows = []
    for _, r in df.iterrows():
        ab = latex_escape(r["Ablasyon Stratejisi"])
        rows.append(
            f"{ab} & {int(r['Toplam Fold'])} & "
            f"${r['Ortalama Başarı (%)']:.2f} \\pm {r['Standart Sapma (%)']:.2f}$ \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table}[t]
\centering
\caption{Aggregate impact of each augmentation/ablation mode, pooled across
all backbones, heads, and tuning strategies (mean$\pm$std accuracy in \%
across all available folds).}
\label{tab:ablation_impact}
\begin{tabular}{lrc}
\toprule
Ablation mode & Fold runs & Accuracy (\%) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write_table(OUT / "T04_ablation_impact.tex", body)


# ---------------------------------------------------------------- T05
def t05_generalization_gap():
    df = pd.read_csv(Q1 / "Q1_Table4_Generalization_Gap.csv", sep=";")
    # Strip percent signs and convert
    for col in ["İç Veri: Mean Acc", "Dış Veri: Zero-Shot Acc", "Generalization Gap"]:
        df[col] = df[col].str.rstrip("%").astype(float)
    # Pick representative subset: best per backbone × FULL/standard/standard
    sub = df[(df["Ablasyon"] == "FULL") & (df["Head"] == "Standard")].copy()
    sub = sub.sort_values("Dış Veri: Zero-Shot Acc", ascending=False).drop_duplicates("Model")
    rows = []
    for _, r in sub.iterrows():
        rows.append(
            f"{latex_escape(r['Model'])} & {latex_escape(r['Tune'])} & "
            f"{r['İç Veri: Mean Acc']:.2f} & {r['Dış Veri: Zero-Shot Acc']:.2f} & "
            f"{r['Generalization Gap']:+.2f} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table}[t]
\centering
\caption{Internal vs.\ external (HaGRID zero-shot) accuracy on the FULL pipeline,
standard head. Negative gap indicates a large drop on the unseen domain
and is the central reviewer-relevant signal of synthetic-to-real distribution
shift. Full results across every (backbone, ablation) cell appear in Table~\ref{tab:gen_gap_full}.}
\label{tab:gen_gap}
\begin{tabular}{llccc}
\toprule
Backbone & Tune & In-dist.\ (\%) & Zero-shot (\%) & Gap (pp) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write_table(OUT / "T05_generalization_gap.tex", body)


# ---------------------------------------------------------------- T06
def t06_tune_strategy_effect():
    df = pd.read_csv(STATS / "pairwise_results.csv")
    sub = df[df["family"] == "C_tune_standard_vs_progressive"].copy()
    rows = []
    for _, r in sub.sort_values("model").iterrows():
        sig = "$^{\\dagger}$" if r["sig_q05"] else ""
        rows.append(
            f"{latex_escape(r['model'])} & {latex_escape(r['ablation'])} & "
            f"${r['mean_standard']*100:.2f}$ & ${r['mean_progressive']*100:.2f}$ & "
            f"${r['delta']*100:+.2f}$ & ${r['hedges_g']:+.2f}$ & "
            f"${r['t_p_raw']:.4f}${sig} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table*}[t]
\centering
\caption{Effect of progressive vs.\ standard fine-tuning, paired across the
same 5 image-grouped folds (per-pair test: paired $t$-test; $^{\dagger}$
denotes BH-FDR adjusted $q<0.05$ within this family). Positive $\Delta$ means
standard fine-tuning is better. The two-sided minimum achievable $p$-value
for paired Wilcoxon at $n{=}5$ is $\approx 0.0625$, so the $t$-test is used
as the primary inferential statistic; full Wilcoxon results are in the
supplementary CSV.}
\label{tab:tune_effect}
\begin{tabular}{llccccc}
\toprule
Backbone & Ablation & Standard (\%) & Progressive (\%) & $\Delta$ (pp) & Hedges' $g$ & $p$ ($t$) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    write_table(OUT / "T06_tune_strategy_effect.tex", body)


# ---------------------------------------------------------------- T07
def t07_head_strategy_effect():
    df = pd.read_csv(STATS / "pairwise_results.csv")
    sub = df[df["family"] == "D_head_vs_standard"].copy()
    rows = []
    for _, r in sub.iterrows():
        sig = "$^{\\dagger}$" if r["sig_q05"] else ""
        rows.append(
            f"{latex_escape(r['head_b'])} & "
            f"${r['mean_standard_head']*100:.2f}$ & ${r['mean_other_head']*100:.2f}$ & "
            f"${r['delta']*100:+.2f}$ & ${r['hedges_g']:+.2f}$ & "
            f"${r['t_p_raw']:.4f}${sig} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table}[t]
\centering
\caption{Classification-head ablation on EfficientNetV2B0 (FULL pipeline,
standard fine-tuning), paired across the same 5 folds. The standard GAP
head outperforms both attention and spatial-pooling variants ($^{\dagger}$
denotes BH-FDR $q<0.05$, paired $t$-test).}
\label{tab:head_effect}
\begin{tabular}{lccccc}
\toprule
Variant & Standard head (\%) & Variant (\%) & $\Delta$ (pp) & Hedges' $g$ & $p$ ($t$) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write_table(OUT / "T07_head_strategy_effect.tex", body)


# ---------------------------------------------------------------- T08
def t08_synthetic_significance():
    df = pd.read_csv(STATS / "pairwise_results.csv")
    sub = df[df["family"] == "A_synth_vs_no_synth"].copy()
    summary = sub.groupby("model").agg(
        n_pairs=("ablation_a", "count"),
        mean_delta=("delta", "mean"),
        max_delta=("delta", "max"),
        min_delta=("delta", "min"),
        mean_d=("hedges_g", "mean"),
        sig_count=("sig_q05", "sum"),
    ).reset_index()
    rows = []
    for _, r in summary.iterrows():
        rows.append(
            f"{latex_escape(r['model'])} & {int(r['n_pairs'])} & "
            f"${r['min_delta']*100:+.2f}$ & ${r['max_delta']*100:+.2f}$ & "
            f"${r['mean_delta']*100:+.2f}$ & ${r['mean_d']:+.2f}$ & "
            f"{int(r['sig_count'])}/{int(r['n_pairs'])} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_tables.py
\begin{table}[t]
\centering
\caption{Effect of the synthetic-augmentation pipeline against the
no-augmentation baseline (NO\_SYNTH), aggregated across all augmentation
modes per backbone. ``Sig.'' counts pairs with BH-FDR $q<0.05$ on the
paired $t$-test. The NO\_SYNTH baseline collapses to $\approx$45--57\%
accuracy in our 4-class setup, while every augmented mode reaches
$\geq$80\%. Note: primary $p$-value is paired $t$-test; Wilcoxon at the $n{=}5$ two-sided floor ($\approx$0.0625) reported in supplementary CSV.}
\label{tab:synth_significance}
\begin{tabular}{lrccccc}
\toprule
Backbone & $n$ pairs & Min $\Delta$ (pp) & Max $\Delta$ (pp) & Mean $\Delta$ (pp) & Mean $g$ & Sig.\ ($q<.05$) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write_table(OUT / "T08_synthetic_significance.tex", body)


def main():
    t01_dataset_inventory()
    t02_model_complexity()
    t03_main_results()
    t04_ablation_impact()
    t05_generalization_gap()
    t06_tune_strategy_effect()
    t07_head_strategy_effect()
    t08_synthetic_significance()
    print(f"\n[INFO] All 8 tables written to: {OUT}")


if __name__ == "__main__":
    main()
