"""
make_none_robustness_table.py - Revision table T16 (abstention robustness).

Builds the per-backbone comparison between the original synthetic ``none`` external
evaluation (V1) and the supplementary evaluation whose ``none`` class includes real
HaGRID non-target hands (V2, produced by ``src/build_external_test_v2.py``).

Inputs  (both under reports/aggregated/):
  global_cross_dataset_evaluation.json       (V1, synthetic none)
  global_cross_dataset_evaluation_v2.json    (V2, real non-target hands)
Output:
  paper/tables/T16_none_robustness.tex
"""
from __future__ import annotations
from pathlib import Path
from collections import defaultdict
import json
import sys

ROOT = Path(__file__).resolve().parents[2]
AGG = ROOT / "reports" / "aggregated"
OUT = ROOT / "paper" / "tables" / "T16_none_robustness.tex"

BACK = ["DenseNet121", "EfficientNetV2B0", "ResNet50", "MobileNetV3Small", "VGG16"]


def _load(name):
    p = AGG / name
    if not p.exists():
        sys.exit(f"[T16] missing {p} (copy the V2 report from revize/ into reports/aggregated/).")
    return json.loads(p.read_text())["model_results"]


def _stats(rep):
    cr = rep["classification_report"]
    return rep["accuracy"], cr["none"]["f1-score"], cr["none"]["recall"]


def _backbone(name):
    return next((b for b in BACK if b.lower() in name.lower()), None)


def _headline(name):
    n = name.lower()
    return "full" in n and "standard_standard" in n


def main():
    v1 = _load("global_cross_dataset_evaluation.json")
    v2 = _load("global_cross_dataset_evaluation_v2.json")
    agg = defaultdict(lambda: {"v1": [], "v2": []})
    for name in v2:
        if not _headline(name):
            continue
        b = _backbone(name)
        if not b:
            continue
        if name in v1:
            agg[b]["v1"].append(_stats(v1[name]))
        agg[b]["v2"].append(_stats(v2[name]))

    def mean(xs, i):
        v = [x[i] for x in xs]
        return sum(v) / len(v) if v else float("nan")

    rows, av1, av2 = [], [], []
    for b in BACK:
        a = agg[b]
        if not a["v2"]:
            continue
        av1 += a["v1"]; av2 += a["v2"]
        rows.append(
            f"{b} & {mean(a['v1'],0)*100:.1f} & {mean(a['v2'],0)*100:.1f} & "
            f"{mean(a['v1'],1)*100:.1f} & {mean(a['v2'],1)*100:.1f} & {mean(a['v2'],2)*100:.1f} \\\\"
        )
    mrow = (f"Mean & {mean(av1,0)*100:.1f} & {mean(av2,0)*100:.1f} & "
            f"{mean(av1,1)*100:.1f} & {mean(av2,1)*100:.1f} & {mean(av2,2)*100:.1f} \\\\")

    body = r"""% Auto-generated by paper/scripts/make_none_robustness_table.py (do not edit by hand).
\begin{table}[!tb]
\centering
\caption{Abstention robustness on the external HaGRID transfer slice for the
\texttt{FULL} pipeline (standard head, standard fine-tuning). V1 uses the
synthetic \texttt{none} class (random-noise and solid-colour tiles); V2 replaces
about one third of \texttt{none} with real HaGRID frames of non-target gestures
(twelve classes). Accuracy and macro \texttt{none} $F_1$ are in \%; \texttt{none}
recall (V2) is the fraction of real non-target hands correctly routed to
\texttt{none}. Means are over the available complete cells per backbone.}
\label{tab:none_robustness}
\begin{tabular}{lccccc}
\toprule
Backbone & Acc.\ V1 & Acc.\ V2 & none $F_1$ V1 & none $F_1$ V2 & none recall V2 \\
\midrule
""" + "\n".join(rows) + "\n\\midrule\n" + mrow + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"[SAVED] {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
