"""
make_extra_tables.py — Tables for the previously-unused Q1 CSV reports.

Adds:
  T09_classwise_zeroshot_topbot.tex   from Q1_Table3
  T10_precision_recall_tradeoff.tex   from Q1_Table6  (top vs bottom slice)
  T11_internal_classwise_stability.tex from Q1_Table7
  T12_kfold_consistency_full.tex      from Q1_Table2  (compact, all 73 configs)
  T13_full_generalization_gap.tex     from Q1_Table4  (best per backbone+ablation)
"""
from __future__ import annotations
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
Q1 = ROOT / "reports" / "aggregated"
OUT = ROOT / "paper" / "tables"
OUT.mkdir(parents=True, exist_ok=True)


def latex_escape(s):
    return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def fmt_pm(s: str) -> str:
    """Convert 'mean ± std' (Unicode ±) to '$mean \\pm std$' for LaTeX."""
    parts = str(s).replace("±", "±").split("±")
    if len(parts) == 2:
        return f"${parts[0].strip()} \\pm {parts[1].strip()}$"
    return latex_escape(s)


def write(path, body):
    path.write_text(body, encoding="utf-8")
    print(f"[SAVED] {path}  ({path.stat().st_size} bytes)")


# ------------------------------------------------------------- T09
def t09_classwise_zeroshot():
    df = pd.read_csv(Q1 / "Q1_Table3_Classwise_ZeroShot_F1_Scores.csv", sep=";")
    # Clean column names
    df.columns = [c.strip() for c in df.columns]
    # Mean per (Model, Ablation, Head, Tune) since each (config, fold) has its own row
    grp = df.groupby(["Model", "Ablasyon", "Head", "Tune"]).agg(
        rock=("Rock (F1)", "mean"),
        paper=("Paper (F1)", "mean"),
        scissors=("Scissors (F1)", "mean"),
        none=("None/Bg (F1)", "mean"),
    ).reset_index()
    grp["mean_4cls"] = grp[["rock", "paper", "scissors", "none"]].mean(axis=1)
    # Top-5 and Bottom-5 by 4-class mean F1
    top = grp.sort_values("mean_4cls", ascending=False).head(5)
    bot = grp.sort_values("mean_4cls").head(5)

    def rows(sub):
        out = []
        for _, r in sub.iterrows():
            out.append(
                f"{latex_escape(r['Model'])} & {latex_escape(r['Ablasyon'])} & "
                f"{latex_escape(r['Tune'])} & "
                f"{r['rock']:.3f} & {r['paper']:.3f} & "
                f"{r['scissors']:.3f} & {r['none']:.3f} & "
                f"\\textbf{{{r['mean_4cls']:.3f}}} \\\\"
            )
        return "\n".join(out)

    body = r"""% Auto-generated by paper/scripts/make_extra_tables.py
\begin{table*}[t]
\centering
\caption{Per-class HaGRID zero-shot F1 (mean over folds): top-5 and
bottom-5 configurations by mean per-class F1 (out of N=104 unique backbone/ablation/head/tune cells). Configurations differ
substantially in how they sacrifice the \texttt{none}/background class
under domain shift.}
\label{tab:classwise_zeroshot}
\begin{tabular}{lllccccc}
\toprule
Backbone & Ablation & Tune & Rock $F_1$ & Paper $F_1$ & Scissors $F_1$ & None $F_1$ & Mean $F_1$ \\
\midrule
\multicolumn{8}{l}{\emph{Top-5 by zero-shot mean $F_1$}} \\
""" + rows(top) + r"""
\midrule
\multicolumn{8}{l}{\emph{Bottom-5 by zero-shot mean $F_1$}} \\
""" + rows(bot) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    write(OUT / "T09_classwise_zeroshot.tex", body)


# ------------------------------------------------------------- T10
def t10_precision_recall_tradeoff():
    df = pd.read_csv(Q1 / "Q1_Table6_Precision_vs_Recall_Tradeoff.csv", sep=";")
    df.columns = [c.strip() for c in df.columns]
    for col in ["Macro Precision", "Macro Recall",
                "Weighted Precision", "Weighted Recall"]:
        df[col] = df[col].str.rstrip("%").astype(float)
    # Aggregate per config (mean across folds), then keep top-5 by Macro F1 proxy
    grp = df.groupby(["Model", "Ablasyon", "Head", "Tune"]).agg(
        macro_p=("Macro Precision", "mean"),
        macro_r=("Macro Recall", "mean"),
        wgt_p=("Weighted Precision", "mean"),
        wgt_r=("Weighted Recall", "mean"),
    ).reset_index()
    grp["macro_f1_proxy"] = (
        2 * grp["macro_p"] * grp["macro_r"] /
        (grp["macro_p"] + grp["macro_r"]).replace(0, 1)
    )
    grp["pr_gap"] = grp["macro_p"] - grp["macro_r"]
    # Show top-5 by macro F1 and the 5 with the largest |P-R| gap
    top = grp.sort_values("macro_f1_proxy", ascending=False).head(5)
    gap = grp.assign(abs_gap=grp["pr_gap"].abs()).sort_values(
        "abs_gap", ascending=False).head(5)

    def rows(sub):
        out = []
        for _, r in sub.iterrows():
            out.append(
                f"{latex_escape(r['Model'])} & {latex_escape(r['Ablasyon'])} & "
                f"{latex_escape(r['Tune'])} & "
                f"{r['macro_p']:.2f} & {r['macro_r']:.2f} & "
                f"{r['pr_gap']:+.2f} & {r['macro_f1_proxy']:.2f} \\\\"
            )
        return "\n".join(out)

    body = r"""% Auto-generated by paper/scripts/make_extra_tables.py
\begin{table*}[t]
\centering
\caption{Macro precision vs.\ macro recall trade-off on the HaGRID
zero-shot test (mean across folds, in \%). Top section: best
configurations by macro $F_1$. Bottom section: configurations with
the largest absolute precision--recall imbalance, indicating
threshold-sensitive operating points (out of N=104 unique backbone/ablation/head/tune cells).}
\label{tab:pr_tradeoff}
\begin{tabular}{lllcccc}
\toprule
Backbone & Ablation & Tune & Macro P & Macro R & P$-$R gap & Macro $F_1$ \\
\midrule
\multicolumn{7}{l}{\emph{Top-5 by macro $F_1$}} \\
""" + rows(top) + r"""
\midrule
\multicolumn{7}{l}{\emph{Top-5 by absolute precision--recall gap}} \\
""" + rows(gap) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    write(OUT / "T10_precision_recall_tradeoff.tex", body)


# ------------------------------------------------------------- T11
def t11_internal_classwise_stability():
    df = pd.read_csv(Q1 / "Q1_Table7_Internal_Classwise_Stability.csv", sep=";")
    df.columns = [c.strip() for c in df.columns]
    # Each row is already (Model, Ablation, Head, Tune); pick representative subset
    # All unique (Model, Ablation, Head, Tune) — show all FULL configs sorted by Backbone
    sub = df[df["Ablasyon"] == "FULL"].copy()
    rows = []
    for _, r in sub.sort_values(["Model", "Tune"]).iterrows():
        rows.append(
            f"{latex_escape(r['Model'])} & {latex_escape(r['Head'])} & "
            f"{latex_escape(r['Tune'])} & "
            f"{fmt_pm(r['Rock F1 (Mean±SD)'])} & "
            f"{fmt_pm(r['Paper F1 (Mean±SD)'])} & "
            f"{fmt_pm(r['Scissors F1 (Mean±SD)'])} & "
            f"{fmt_pm(r['Background F1 (Mean±SD)'])} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_extra_tables.py
\begin{table*}[t]
\centering
\caption{Internal per-class $F_1$ (\%) stability across the five
image-grouped folds for every backbone/head/tune cell on the
\texttt{FULL} pipeline (mean$\pm$SD).}
\label{tab:classwise_stability}
\begin{tabular}{lllcccc}
\toprule
Backbone & Head & Tune & Rock $F_1$ & Paper $F_1$ & Scissors $F_1$ & None $F_1$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    write(OUT / "T11_internal_classwise_stability.tex", body)


# ------------------------------------------------------------- T12
def t12_kfold_consistency_full():
    df = pd.read_csv(Q1 / "Q1_Table2_KFold_Statistical_Consistency.csv", sep=";")
    df.columns = [c.strip() for c in df.columns]
    df = df.sort_values("Ort. Başarı ± SS (%)", ascending=False)
    rows = []
    for _, r in df.iterrows():
        rows.append(
            f"{latex_escape(r['Model'])} & {latex_escape(r['Ablasyon'])} & "
            f"{latex_escape(r['Head'])} & {latex_escape(r['Tune'])} & "
            f"{int(r['Fold Sayısı'])} & "
            f"{latex_escape(r['Ort. Başarı ± SS (%)'])} & "
            f"{latex_escape(r['Ort. F1 Skor ± SS (%)'])} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_extra_tables.py
\begin{longtable}{llllrcc}
\caption{Five-fold cross-validation accuracy and macro-$F_1$ for every
configuration evaluated in this study (mean$\pm$SD, \%). Configurations
are sorted by mean accuracy. Use of \texttt{longtable} is intended for
the supplementary material.} \label{tab:kfold_full} \\
\toprule
Backbone & Ablation & Head & Tune & Folds & Acc.\ (\%) & Macro-$F_1$ (\%) \\
\midrule
\endfirsthead
\toprule
Backbone & Ablation & Head & Tune & Folds & Acc.\ (\%) & Macro-$F_1$ (\%) \\
\midrule
\endhead
\bottomrule
\endfoot
""" + "\n".join(rows) + r"""
\end{longtable}
"""
    write(OUT / "T12_kfold_consistency_full.tex", body)


# ------------------------------------------------------------- T13
def t13_full_generalization_gap():
    """Pick best per (Backbone, Ablation) pair on zero-shot accuracy."""
    df = pd.read_csv(Q1 / "Q1_Table4_Generalization_Gap.csv", sep=";")
    for col in ["İç Veri: Mean Acc", "Dış Veri: Zero-Shot Acc",
                "Generalization Gap"]:
        df[col] = df[col].str.rstrip("%").astype(float)
    sub = (df.sort_values("Dış Veri: Zero-Shot Acc", ascending=False)
             .drop_duplicates(["Model", "Ablasyon"]))
    sub = sub.sort_values(["Model", "Ablasyon"]).reset_index(drop=True)
    rows = []
    for _, r in sub.iterrows():
        rows.append(
            f"{latex_escape(r['Model'])} & {latex_escape(r['Ablasyon'])} & "
            f"{latex_escape(r['Head'])} & {latex_escape(r['Tune'])} & "
            f"{r['İç Veri: Mean Acc']:.2f} & "
            f"{r['Dış Veri: Zero-Shot Acc']:.2f} & "
            f"{r['Generalization Gap']:+.2f} \\\\"
        )

    body = r"""% Auto-generated by paper/scripts/make_extra_tables.py
\begin{table*}[t]
\centering
\caption{Best (by HaGRID zero-shot accuracy) head/tune setting for
every (backbone, ablation) pair: in-distribution accuracy, zero-shot
accuracy, and generalisation gap (\%, percentage points). Sorted
alphabetically by backbone then ablation.}
\label{tab:gen_gap_full}
\begin{tabular}{llllccc}
\toprule
Backbone & Ablation & Head & Tune & In-dist.\ (\%) & Zero-shot (\%) & Gap (pp) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    write(OUT / "T13_full_generalization_gap.tex", body)


def main():
    t09_classwise_zeroshot()
    t10_precision_recall_tradeoff()
    t11_internal_classwise_stability()
    t12_kfold_consistency_full()
    t13_full_generalization_gap()
    print(f"\n[INFO] 5 extra tables written to: {OUT}")


if __name__ == "__main__":
    main()
