"""
make_multiseed_table.py - Revision table T17 (multi-seed seed stability).

Reads the aggregated multi-seed summary (produced by src/aggregate_multiseed.py)
and emits the booktabs table reported as Table T17: the FULL pipeline (standard
head, standard fine-tuning) for every backbone, with each random seed's grouped
five-fold mean validation accuracy and the across-seed mean +/- standard deviation.
Only FULL cells are tabulated, matching the table in the paper; the released summary
JSON additionally contains the other re-seeded cells.

Input (first existing path is used):
  reports/aggregated/multiseed_summary.json   (released location)
  reports_multiseed/multiseed_summary.json     (fresh-run location)
Output:
  paper/tables/T17_multiseed_stability.tex
"""
from __future__ import annotations
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[2]
SUMMARY_CANDIDATES = [
    ROOT / "reports" / "aggregated" / "multiseed_summary.json",
    ROOT / "reports_multiseed" / "multiseed_summary.json",
]
OUT = ROOT / "paper" / "tables" / "T17_multiseed_stability.tex"

BACKBONES = ["DenseNet121", "EfficientNetV2B0", "ResNet50", "MobileNetV3Small", "VGG16"]
ABLATION = "FULL"

CAPTION = (
    r"Seed robustness of the \texttt{FULL} pipeline (standard head and standard "
    r"fine-tuning). Each column reports the grouped five-fold mean validation accuracy "
    r"(\%) for one random seed; the last column is the across-seed mean\,$\pm$\,standard "
    r"deviation. Seed~42 is the configuration used in the main experiments. The across-seed "
    r"standard deviation is approximately 0.02~pp, confirming that the reported results are "
    r"not seed-dependent. These re-runs were performed in a fresh environment and reproduce "
    r"the main-text accuracies to within $0.2$~pp; the seed variance itself is the quantity "
    r"of interest here."
)


def main():
    summary = next((p for p in SUMMARY_CANDIDATES if p.exists()), None)
    if summary is None:
        sys.exit("[T17] missing multiseed_summary.json (looked in "
                 f"{[str(p) for p in SUMMARY_CANDIDATES]}); run src/aggregate_multiseed.py first.")
    cells = json.loads(summary.read_text())["cells"]

    full = {c["model"]: c for c in cells.values()
            if c["ablation"].upper() == ABLATION
            and c["head"] == "standard" and c["tune"] == "standard"}
    present = [b for b in BACKBONES if b in full]
    if not present:
        sys.exit(f"[T17] no {ABLATION} standard/standard cells found in {summary}.")

    seeds = sorted({s for b in present for s in full[b]["seeds_used"]})
    seed_cols = " & ".join(f"seed~{s}" for s in seeds)

    rows = []
    for b in present:
        c = full[b]
        psm = {int(k): v for k, v in c["per_seed_mean"].items()}
        vals = " & ".join(f"{psm[s] * 100:.2f}" if s in psm else "--" for s in seeds)
        rows.append(f"{b} & {vals} & {c['across_seed_mean'] * 100:.2f}"
                    f"$\\,\\pm\\,${c['across_seed_std'] * 100:.2f} \\\\")

    body = (
        "% Auto-generated by paper/scripts/make_multiseed_table.py (do not edit by hand).\n"
        "\\begin{table}[!tb]\n\\centering\n"
        "\\caption{" + CAPTION + "}\n"
        "\\label{tab:multiseed_stability}\n"
        "\\begin{tabular}{l" + "c" * len(seeds) + "c}\n\\toprule\n"
        "Backbone & " + seed_cols + " & mean\\,$\\pm$\\,std \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"[SAVED] {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
